---
title: "Capstone Project Model Analysis"
author: "Eli Nimy"
date: "18/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r message=FALSE, warning=FALSE}
library(shiny)
library(shinydashboard)
library(shinydashboardPlus)
library(stringr)
library(tidyverse)
library(lubridate)
library(hms)
library(scales)
library(highcharter)
library(stringr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(hms)
library(scales)
library(plotly)
library(car)
library(rgl)
library(ggcorrplot)
library(xts)
library(dygraphs)
library(taRifx)
library(xlsx)
```


## Model 1 
```{r warning=FALSE, message=FALSE}
data1 <- read.xlsx2('C:/Users/Student/crime-activity-classification/Image_Data_Model_1.xlsx',
                    sheetIndex = 1)
```

## Model 2
```{r}
data2 <- read.xlsx2('C:/Users/Student/crime-activity-classification/Image_Data_Model_2.xlsx',
                    sheetIndex = 1)
```


## MODEL 1
### Change names 
```{r}
"Image" -> names(data1)[1]
"Arson" -> names(data1)[2]
```

### Change datatypes 
```{r}
data1$Arson <- as.numeric(as.character(data1$Arson))
data1$Assault <- as.numeric(as.character(data1$Assault))
data1$Weapon <- as.numeric(as.character(data1$Weapon))
```

### filtering data

```{r}
Arson_class_average1 <- data1 %>% 
  filter(Image == 'arson') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Weapon_Average = mean(Weapon))
Arson_class_average1
```

```{r}
Assault_class_average1 <- data1 %>% 
  filter(Image == 'assault') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Weapon_Average = mean(Weapon))
Assault_class_average1
```

```{r}
Weapon_class_average1 <- data1 %>% 
  filter(Image == 'weapon') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Weapon_Average = mean(Weapon))
Weapon_class_average1
```

### Model classes 
```{r}
Arson_class1 <- data1 %>% 
  filter(Image == 'arson')
Arson_class1
```

```{r}
Assault_class1 <- data1 %>% 
  filter(Image == 'assault')
Assault_class1
```

```{r}
Weapon_class1 <- data1 %>% 
  filter(Image == 'weapon')
Weapon_class1
```

## MODEL 2

### Change names 
```{r}
"Image" -> names(data2)[1]
"Arson" -> names(data2)[2]
```

### Change datatypes 
```{r}
data2$Arson <- as.numeric(as.character(data2$Arson))
data2$Assault <- as.numeric(as.character(data2$Assault))
data2$Normal <- as.numeric(as.character(data2$Normal))
data2$Weapon <- as.numeric(as.character(data2$Weapon))
```

### filtering data

```{r}
Arson_class_average2 <- data2 %>% 
  filter(Image == 'arson') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Normal_Average = mean(Normal),
            Weapon_Average = mean(Weapon))
Arson_class_average2
```

```{r}
Assault_class_average2 <- data2 %>% 
  filter(Image == 'assault') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Normal_Average = mean(Normal),
            Weapon_Average = mean(Weapon))
Assault_class_average2
```

```{r}
Normal_class_average2 <- data2 %>% 
  filter(Image == 'normal') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Normal_Average = mean(Normal),
            Weapon_Average = mean(Weapon))
Normal_class_average2
```

```{r}
Weapon_class_average2 <- data2 %>% 
  filter(Image == 'weapon') %>% 
  summarise(Arson_Average = mean(Arson),
            Assault_Average = mean(Assault),
            Weapon_Average = mean(Weapon))
Weapon_class_average2
```

### Model classes 
```{r}
Arson_class2 <- data2 %>% 
  filter(Image == 'arson')
Arson_class2
```

```{r}
Assault_class2 <- data2 %>% 
  filter(Image == 'assault')
Assault_class2
```

```{r}
Normal_class2 <- data2 %>% 
  filter(Image == 'normal')
Normal_class2
```

```{r}
Weapon_class2 <- data2 %>% 
  filter(Image == 'weapon')
Weapon_class2
```

```{r}
data2
```



```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

